=== nicolaszy/ws3C/data/gallery.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   xmlns="https://christian-seiler.github.io/ws3C"
		   targetNamespace="https://christian-seiler.github.io/ws3C"
		   elementFormDefault="qualified">

	<xs:element name="title" type="xs:string"/>
	<xs:element name="image" type="xs:string"/>


	<xs:element name="slide">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title"/>
				<xs:element ref="image"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="gallery">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="slide" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nicolaszy/ws3C/data/gallery.xml
<?xml version="1.0" encoding="UTF-8"?>
<gallery xmlns="https://christian-seiler.github.io/ws3C"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="https://christian-seiler.github.io/ws3C
        gallery.xsd">
	<slide>
		<title>RhB Tm 2/2 91 Spur H0n</title>
		<image>feac-1.jpg</image>
	</slide>
	<slide>
		<title>SBB Cargo Re 6/6 620 11655 Spur H0</title>
		<image>feac-2.jpg</image>
	</slide>
	<slide>
		<title>Jura Cement AG Wildegg Spur H0</title>
		<image>feac-3.jpg</image>
	</slide>
	<slide>
		<title>Spur H0</title>
		<image>feac-4.jpg</image>
	</slide>
	<slide>
		<title>SBB E 3/3 8586 Spur 0</title>
		<image>feac-5.jpg</image>
	</slide>
	<slide>
		<title>DB BR44 339 Spur 0</title>
		<image>feac-6.jpg</image>
	</slide>
	<slide>
		<title>BLS Ae 6/8 205</title>
		<image>feac-7.jpg</image>
	</slide>
</gallery>
