=== nicolaszy/ws3C/data/partner.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   xmlns="https://christian-seiler.github.io/ws3C"
		   targetNamespace="https://christian-seiler.github.io/ws3C"
		   elementFormDefault="qualified">

	<xs:element name="title" type="xs:string"/>
	<xs:element name="image" type="xs:string"/>
	<xs:element name="url" type="xs:string"/>


	<xs:element name="friend">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title"/>
				<xs:element ref="image" minOccurs="0"/>
				<xs:element ref="url" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="sponsor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title"/>
				<xs:element ref="image" minOccurs="0"/>
				<xs:element ref="url" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="partner">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sponsor" maxOccurs="unbounded" minOccurs="0"/>
				<xs:element ref="friend" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nicolaszy/ws3C/data/partner.xml
<?xml version="1.0" encoding="UTF-8"?>
<partner xmlns="https://christian-seiler.github.io/ws3C"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="https://christian-seiler.github.io/ws3C
        partner.xsd">

	<sponsor>
		<title>Raiffeisen</title>
		<image>raiffeisen.png</image>
		<url>www.raiffeisen.ch/wohlen</url>
	</sponsor>
	<sponsor>
		<title>A. Käppeli's Söhne AG</title>
		<image>kaeppeli.png</image>
	</sponsor>
	<sponsor>
		<title>Gemeinde Wohlen</title>
		<image>wohlen.png</image>
		<url>wohlen.ch</url>
	</sponsor>
	<sponsor>
		<title>Wohler Anzeiger</title>
		<image>wohleranzeiger.png</image>
		<url>wohleranzeiger.ch</url>
	</sponsor>
	<friend>
		<title>Brugger Modelleisenbahn-Club</title>
		<image>bmc.png</image>
		<url>bmc-brugg.ch</url>
	</friend>
	<friend>
		<title>Eisenbahn-Modellbau-Club Aarau</title>
		<image>emca.png</image>
		<url>emcaarau.ch</url>
	</friend>
	<friend>
		<title>Schweizerischen Verband Eisenbahn-Amateur SVEA</title>
		<image>svea.png</image>
		<url>svea-asea.ch</url>
	</friend>
</partner>
